env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:jsx-a11y/recommended
  - plugin:import/recommended
  - airbnb
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
  import/no-unresolved: 0
  no-console: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]